Aplicacao-WEB/src/main/java/classesJSF/MovimentoController.java
package classesJSF;

import modelo.Movimento;
import classesJSF.util.JsfUtil;
import classesJSF.util.PaginationHelper;
import beanSessao.MovimentoFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import modelo.Produto;

@Named("movimentoController")
@SessionScoped
public class MovimentoController implements Serializable {

    private Movimento current;
    private DataModel items = null;
    @EJB
    private beanSessao.MovimentoFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public MovimentoController() {
    }

    public Movimento getSelected() {
        if (current == null) {
            current = new Movimento();
            selectedItemIndex = -1;
        }
        return current;
    }

    private MovimentoFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Movimento) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Movimento();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("MovimentoCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Movimento) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("MovimentoUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Movimento) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("MovimentoDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        items = null;
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Movimento getMovimento(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Movimento.class)
    public static class MovimentoControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            MovimentoController controller = (MovimentoController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "movimentoController");
            return controller.getMovimento(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Movimento) {
                Movimento o = (Movimento) object;
                return getStringKey(o.getCodMovimento());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Movimento.class.getName());
            }
        }
    }
}

Aplicacao-WEB/src/main/webapp/paginasJSF/movimento/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateMovimentoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateMovimentoLabel_codMovimento}" for="codMovimento" />
                    <h:inputText id="codMovimento" value="#{movimentoController.selected.codMovimento}" title="#{bundle.CreateMovimentoTitle_codMovimento}" required="true" requiredMessage="#{bundle.CreateMovimentoRequiredMessage_codMovimento}"/>
                    <h:outputLabel value="#{bundle.CreateMovimentoLabel_quantidade}" for="quantidade" />
                    <h:inputText id="quantidade" value="#{movimentoController.selected.quantidade}" title="#{bundle.CreateMovimentoTitle_quantidade}" required="true" requiredMessage="#{bundle.CreateMovimentoRequiredMessage_quantidade}"/>
                    <h:outputLabel value="#{bundle.CreateMovimentoLabel_dataCadastro}" for="dataCadastro" />
                    <h:inputText id="dataCadastro" value="#{movimentoController.selected.dataCadastro}" title="#{bundle.CreateMovimentoTitle_dataCadastro}" required="true" requiredMessage="#{bundle.CreateMovimentoRequiredMessage_dataCadastro}">
                        <f:convertDateTime pattern="dd/MM/yyyy" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.CreateMovimentoLabel_codTipo}" for="codTipo" />
                    <h:selectOneMenu id="codTipo" value="#{movimentoController.selected.codTipo}" title="#{bundle.CreateMovimentoTitle_codTipo}" required="true" requiredMessage="#{bundle.CreateMovimentoRequiredMessage_codTipo}">
                        <f:selectItems value="#{tipoMovimentoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateMovimentoLabel_codProduto}" for="codProduto" />
                    <h:selectOneMenu id="codProduto" value="#{movimentoController.selected.codProduto}" title="#{bundle.CreateMovimentoTitle_codProduto}" required="true" requiredMessage="#{bundle.CreateMovimentoRequiredMessage_codProduto}">
                        <f:selectItems value="#{produtoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{movimentoController.create}" value="#{bundle.CreateMovimentoSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{movimentoController.prepareList}" value="#{bundle.CreateMovimentoShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateMovimentoIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Aplicacao-WEB/src/main/webapp/paginasJSF/movimento/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditMovimentoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditMovimentoLabel_codMovimento}" for="codMovimento" />
                    <h:inputText id="codMovimento" value="#{movimentoController.selected.codMovimento}" title="#{bundle.EditMovimentoTitle_codMovimento}" required="true" requiredMessage="#{bundle.EditMovimentoRequiredMessage_codMovimento}"/>
                    <h:outputLabel value="#{bundle.EditMovimentoLabel_quantidade}" for="quantidade" />
                    <h:inputText id="quantidade" value="#{movimentoController.selected.quantidade}" title="#{bundle.EditMovimentoTitle_quantidade}" required="true" requiredMessage="#{bundle.EditMovimentoRequiredMessage_quantidade}"/>
                    <h:outputLabel value="#{bundle.EditMovimentoLabel_dataCadastro}" for="dataCadastro" />
                    <h:inputText id="dataCadastro" value="#{movimentoController.selected.dataCadastro}" title="#{bundle.EditMovimentoTitle_dataCadastro}" required="true" requiredMessage="#{bundle.EditMovimentoRequiredMessage_dataCadastro}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditMovimentoLabel_codTipo}" for="codTipo" />
                    <h:selectOneMenu id="codTipo" value="#{movimentoController.selected.codTipo}" title="#{bundle.EditMovimentoTitle_codTipo}" required="true" requiredMessage="#{bundle.EditMovimentoRequiredMessage_codTipo}">
                        <f:selectItems value="#{tipoMovimentoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditMovimentoLabel_codProduto}" for="codProduto" />
                    <h:selectOneMenu id="codProduto" value="#{movimentoController.selected.codProduto}" title="#{bundle.EditMovimentoTitle_codProduto}" required="true" requiredMessage="#{bundle.EditMovimentoRequiredMessage_codProduto}">
                        <f:selectItems value="#{produtoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{movimentoController.update}" value="#{bundle.EditMovimentoSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditMovimentoViewLink}"/>
                <br />
                <h:commandLink action="#{movimentoController.prepareList}" value="#{bundle.EditMovimentoShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditMovimentoIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Aplicacao-WEB/src/main/webapp/paginasJSF/movimento/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListMovimentoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListMovimentoEmpty}" rendered="#{movimentoController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{movimentoController.items.rowCount > 0}">
                    <h:outputText value="#{movimentoController.pagination.pageFirstItem + 1}..#{movimentoController.pagination.pageLastItem + 1}/#{movimentoController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{movimentoController.previous}" value="#{bundle.Previous} #{movimentoController.pagination.pageSize}" rendered="#{movimentoController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{movimentoController.next}" value="#{bundle.Next} #{movimentoController.pagination.pageSize}" rendered="#{movimentoController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{movimentoController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListMovimentoTitle_codMovimento}"/>
                            </f:facet>
                            <h:outputText value="#{item.codMovimento}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListMovimentoTitle_quantidade}"/>
                            </f:facet>
                            <h:outputText value="#{item.quantidade}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListMovimentoTitle_dataCadastro}"/>
                            </f:facet>
                            <h:outputText value="#{item.dataCadastro}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListMovimentoTitle_codTipo}"/>
                            </f:facet>
                            <h:outputText value="#{item.codTipo}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListMovimentoTitle_codProduto}"/>
                            </f:facet>
                            <h:outputText value="#{item.codProduto}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{movimentoController.prepareView}" value="#{bundle.ListMovimentoViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{movimentoController.prepareEdit}" value="#{bundle.ListMovimentoEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{movimentoController.destroy}" value="#{bundle.ListMovimentoDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{movimentoController.prepareCreate}" value="#{bundle.ListMovimentoCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListMovimentoIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Aplicacao-WEB/src/main/webapp/paginasJSF/movimento/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewMovimentoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewMovimentoLabel_codMovimento}"/>
                    <h:outputText value="#{movimentoController.selected.codMovimento}" title="#{bundle.ViewMovimentoTitle_codMovimento}"/>
                    <h:outputText value="#{bundle.ViewMovimentoLabel_quantidade}"/>
                    <h:outputText value="#{movimentoController.selected.quantidade}" title="#{bundle.ViewMovimentoTitle_quantidade}"/>
                    <h:outputText value="#{bundle.ViewMovimentoLabel_dataCadastro}"/>
                    <h:outputText value="#{movimentoController.selected.dataCadastro}" title="#{bundle.ViewMovimentoTitle_dataCadastro}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:outputText>
                    <h:outputText value="#{bundle.ViewMovimentoLabel_codTipo}"/>
                    <h:outputText value="#{movimentoController.selected.codTipo}" title="#{bundle.ViewMovimentoTitle_codTipo}"/>
                    <h:outputText value="#{bundle.ViewMovimentoLabel_codProduto}"/>
                    <h:outputText value="#{movimentoController.selected.codProduto}" title="#{bundle.ViewMovimentoTitle_codProduto}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{movimentoController.destroyAndView}" value="#{bundle.ViewMovimentoDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewMovimentoEditLink}"/>
                <br />
                <h:commandLink action="#{movimentoController.prepareCreate}" value="#{bundle.ViewMovimentoCreateLink}" />
                <br />
                <h:commandLink action="#{movimentoController.prepareList}" value="#{bundle.ViewMovimentoShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewMovimentoIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>